---

# Download Required Packages
- name: Apt Pkg
  ansible.builtin.include_tasks: apt-pkg.yml

# Configure SFTP
- name: Sftp
  ansible.builtin.include_tasks: sftp.yml

# User Configurations
- name: User
  ansible.builtin.include_tasks: user.yml

# Setup and Mount S3FS
- name: S3Fs
  ansible.builtin.include_tasks: s3fs.yml
