---
- name: SFTP-Server | Restart sshd
  service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted
  ignore_errors: true

- name: restart s3fs
  become: true
  service:
    name: s3fs
    state: restarted
    enabled: yes
